version: '3'

services:
  challenge:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: ["bash", "/entrypoint.sh"]
    environment:
      USERNAME: nicedev
      PASSWORD: cyberQuest{N3v3r_Pu5h_53cr375_6a4a55b29fa5de2b94d673908f9d46c1}