version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  flag-data:

networks:
  default:
    driver: bridge 
