version: '3.8'

services:
  vuln:
    build: .
    ports:
      - "1337:1337"
    security_opt:
      - no-new-privileges:true
    cap_add:
      - SYS_ADMIN
    user: root
    networks:
      - no-internet
      
networks:
  no-internet:
    internal: true